### ISSUE TITLE
SImplify ExtConf.php

### ISSUE THREAD

**Issue by georgringer** [froemken/plesk_widget#6]
Just by reading:

- remove setters and just set the properties directly. as there are not that many, I would use that explicit to be able to use correct type casting
- `ExtensionConfiguration::class)->get('plesk_widget')` can throw an exception, should be in a try catch block

**Comment by froemken** [comment]
Hi @georgringer 

I have removed the setters from ExtConf and added all these Exception classes into the try-catch block.

Have a cool start into this weekend

Stefan
