### ISSUE TITLE
ext dashboard as requirement

### ISSUE THREAD

**Issue by georgringer** [froemken/plesk_widget#7]
shouldn't be ext:dashboard a hard requirement in ext_emconf + composer.json?

**Comment by froemken** [comment]
Hi @georgringer 

sure...haven't seen dashboard deactivated since 1,5 years, now. So, was never a problem ;-) But of cause, it should be part a requirement for this extension. Thank you for your help to make this a better extension ;-)

Have a pretty cool evening

Stefan
